version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "America/Chicago"
    commit_message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
