version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "live"
    commit_message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
